CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "Chats" (
        "Id" uuid NOT NULL,
        "Name" character varying(150) NOT NULL,
        "Type" integer NOT NULL,
        "Region" character varying(100),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Chats" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "AvatarUrl" character varying(500),
        "Region" character varying(100),
        "About" character varying(1000),
        "IsBlocked" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "WeatherCaches" (
        "Id" uuid NOT NULL,
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "ForecastDate" timestamp with time zone NOT NULL,
        "Temperature" numeric(8,2) NOT NULL,
        "WindSpeed" numeric(8,2) NOT NULL,
        "Pressure" numeric(8,2) NOT NULL,
        "Humidity" numeric(8,2) NOT NULL,
        "Description" character varying(300),
        "LoadedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_WeatherCaches" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "ChatMessages" (
        "Id" uuid NOT NULL,
        "ChatId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Text" character varying(4000) NOT NULL,
        "SentAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatMessages_Chats_ChatId" FOREIGN KEY ("ChatId") REFERENCES "Chats" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ChatMessages_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "CompanionRequests" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" character varying(2000),
        "Region" character varying(100),
        "PlannedDate" timestamp with time zone NOT NULL,
        "MeetingPoint" character varying(200),
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CompanionRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CompanionRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "FishingEntries" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" character varying(2000),
        "FishingDate" timestamp with time zone NOT NULL,
        "LocationName" character varying(200),
        "Latitude" double precision,
        "Longitude" double precision,
        "CatchType" character varying(100),
        "CatchWeight" numeric(10,2),
        "Bait" character varying(100),
        "WeatherSummary" character varying(300),
        "PhotoUrl" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FishingEntries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FishingEntries_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "ModerationLogs" (
        "Id" uuid NOT NULL,
        "AdminUserId" uuid NOT NULL,
        "Action" character varying(100) NOT NULL,
        "EntityType" character varying(100) NOT NULL,
        "EntityId" uuid NOT NULL,
        "Reason" character varying(1000),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ModerationLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ModerationLogs_Users_AdminUserId" FOREIGN KEY ("AdminUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "PointsOfInterest" (
        "Id" uuid NOT NULL,
        "CreatedByUserId" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(2000),
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "Type" integer NOT NULL,
        "Region" character varying(100),
        "IsApproved" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PointsOfInterest" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PointsOfInterest_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE TABLE "CompanionResponses" (
        "Id" uuid NOT NULL,
        "RequestId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Message" character varying(1000),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CompanionResponses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CompanionResponses_CompanionRequests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "CompanionRequests" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CompanionResponses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_ChatMessages_ChatId" ON "ChatMessages" ("ChatId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_ChatMessages_UserId" ON "ChatMessages" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_CompanionRequests_UserId" ON "CompanionRequests" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_CompanionResponses_RequestId" ON "CompanionResponses" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_CompanionResponses_UserId" ON "CompanionResponses" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_FishingEntries_UserId" ON "FishingEntries" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_ModerationLogs_AdminUserId" ON "ModerationLogs" ("AdminUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "IX_PointsOfInterest_CreatedByUserId" ON "PointsOfInterest" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328063650_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260328063650_InitialCreate', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415075740_AddFishingEntryVisibility') THEN
    ALTER TABLE "FishingEntries" ADD "IsPublishedToFeed" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415075740_AddFishingEntryVisibility') THEN
    ALTER TABLE "FishingEntries" ADD "Visibility" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415075740_AddFishingEntryVisibility') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260415075740_AddFishingEntryVisibility', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415095727_AddFriendships') THEN
    CREATE TABLE "Friendships" (
        "Id" uuid NOT NULL,
        "RequesterId" uuid NOT NULL,
        "AddresseeId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Friendships" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Friendships_Users_AddresseeId" FOREIGN KEY ("AddresseeId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Friendships_Users_RequesterId" FOREIGN KEY ("RequesterId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415095727_AddFriendships') THEN
    CREATE INDEX "IX_Friendships_AddresseeId" ON "Friendships" ("AddresseeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415095727_AddFriendships') THEN
    CREATE UNIQUE INDEX "IX_Friendships_RequesterId_AddresseeId" ON "Friendships" ("RequesterId", "AddresseeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415095727_AddFriendships') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260415095727_AddFriendships', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415115952_AddPersonalChats') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260415115952_AddPersonalChats', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415125336_AddPrivateChatUsers') THEN
    ALTER TABLE "Chats" ADD "FirstUserId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415125336_AddPrivateChatUsers') THEN
    ALTER TABLE "Chats" ADD "SecondUserId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415125336_AddPrivateChatUsers') THEN
    CREATE INDEX "IX_Chats_Type_FirstUserId_SecondUserId" ON "Chats" ("Type", "FirstUserId", "SecondUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415125336_AddPrivateChatUsers') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260415125336_AddPrivateChatUsers', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416070002_AddReplyToChatMessages') THEN
    ALTER TABLE "ChatMessages" ADD "ReplyToMessageId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416070002_AddReplyToChatMessages') THEN
    CREATE INDEX "IX_ChatMessages_ReplyToMessageId" ON "ChatMessages" ("ReplyToMessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416070002_AddReplyToChatMessages') THEN
    ALTER TABLE "ChatMessages" ADD CONSTRAINT "FK_ChatMessages_ChatMessages_ReplyToMessageId" FOREIGN KEY ("ReplyToMessageId") REFERENCES "ChatMessages" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416070002_AddReplyToChatMessages') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260416070002_AddReplyToChatMessages', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416090432_AddChatMessageDeleteModes') THEN
    ALTER TABLE "ChatMessages" ADD "DeletedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416090432_AddChatMessageDeleteModes') THEN
    ALTER TABLE "ChatMessages" ADD "IsDeletedForAll" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416090432_AddChatMessageDeleteModes') THEN
    CREATE TABLE "HiddenChatMessages" (
        "Id" uuid NOT NULL,
        "MessageId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "HiddenAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_HiddenChatMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HiddenChatMessages_ChatMessages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "ChatMessages" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_HiddenChatMessages_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416090432_AddChatMessageDeleteModes') THEN
    CREATE UNIQUE INDEX "IX_HiddenChatMessages_MessageId_UserId" ON "HiddenChatMessages" ("MessageId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416090432_AddChatMessageDeleteModes') THEN
    CREATE INDEX "IX_HiddenChatMessages_UserId" ON "HiddenChatMessages" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416090432_AddChatMessageDeleteModes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260416090432_AddChatMessageDeleteModes', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    ALTER TABLE "Chats" ADD "AvatarUrl" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    ALTER TABLE "Chats" ADD "CanMembersInvite" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    ALTER TABLE "Chats" ADD "CreatedByUserId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    ALTER TABLE "Chats" ADD "Description" character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    ALTER TABLE "Chats" ADD "InviteCode" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    CREATE TABLE "ChatParticipants" (
        "Id" uuid NOT NULL,
        "ChatId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Role" integer NOT NULL,
        "JoinedAt" timestamp with time zone NOT NULL,
        "IsMuted" boolean NOT NULL,
        CONSTRAINT "PK_ChatParticipants" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatParticipants_Chats_ChatId" FOREIGN KEY ("ChatId") REFERENCES "Chats" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ChatParticipants_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    CREATE INDEX "IX_Chats_CreatedByUserId" ON "Chats" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    CREATE UNIQUE INDEX "IX_Chats_InviteCode" ON "Chats" ("InviteCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    CREATE UNIQUE INDEX "IX_ChatParticipants_ChatId_UserId" ON "ChatParticipants" ("ChatId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    CREATE INDEX "IX_ChatParticipants_UserId" ON "ChatParticipants" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    ALTER TABLE "Chats" ADD CONSTRAINT "FK_Chats_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416110149_AddGroupChatsStructure') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260416110149_AddGroupChatsStructure', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416112012_AddGroupChatsCore') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260416112012_AddGroupChatsCore', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418052725_AddPrivateChatUserStates') THEN
    CREATE TABLE "PrivateChatUserStates" (
        "Id" uuid NOT NULL,
        "ChatId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "ClearedAt" timestamp with time zone,
        CONSTRAINT "PK_PrivateChatUserStates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PrivateChatUserStates_Chats_ChatId" FOREIGN KEY ("ChatId") REFERENCES "Chats" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PrivateChatUserStates_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418052725_AddPrivateChatUserStates') THEN
    CREATE UNIQUE INDEX "IX_PrivateChatUserStates_ChatId_UserId" ON "PrivateChatUserStates" ("ChatId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418052725_AddPrivateChatUserStates') THEN
    CREATE INDEX "IX_PrivateChatUserStates_UserId" ON "PrivateChatUserStates" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418052725_AddPrivateChatUserStates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260418052725_AddPrivateChatUserStates', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418063516_AddGroupChatSoftDeleteAndParticipantStatus') THEN
    ALTER TABLE "Chats" ADD "DeletedByOwnerAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418063516_AddGroupChatSoftDeleteAndParticipantStatus') THEN
    ALTER TABLE "Chats" ADD "DeletedByOwnerUserId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418063516_AddGroupChatSoftDeleteAndParticipantStatus') THEN
    ALTER TABLE "Chats" ADD "IsDeletedByOwner" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418063516_AddGroupChatSoftDeleteAndParticipantStatus') THEN
    ALTER TABLE "ChatParticipants" ADD "Status" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418063516_AddGroupChatSoftDeleteAndParticipantStatus') THEN
    ALTER TABLE "ChatParticipants" ADD "StatusChangedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418063516_AddGroupChatSoftDeleteAndParticipantStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260418063516_AddGroupChatSoftDeleteAndParticipantStatus', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423134944_AddChatMessageAttachments') THEN
    CREATE TABLE "ChatMessageAttachments" (
        "Id" uuid NOT NULL,
        "ChatMessageId" uuid NOT NULL,
        "FileName" character varying(255) NOT NULL,
        "StoredFileName" character varying(255) NOT NULL,
        "FileUrl" character varying(1000) NOT NULL,
        "ContentType" character varying(255) NOT NULL,
        "Size" bigint NOT NULL,
        "AttachmentType" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ChatMessageAttachments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatMessageAttachments_ChatMessages_ChatMessageId" FOREIGN KEY ("ChatMessageId") REFERENCES "ChatMessages" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423134944_AddChatMessageAttachments') THEN
    CREATE INDEX "IX_ChatMessageAttachments_ChatMessageId" ON "ChatMessageAttachments" ("ChatMessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423134944_AddChatMessageAttachments') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260423134944_AddChatMessageAttachments', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428094848_AddFishingEntryTimeRange') THEN
    DROP INDEX "IX_FishingEntries_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428094848_AddFishingEntryTimeRange') THEN
    ALTER TABLE "FishingEntries" ADD "FishingEndedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428094848_AddFishingEntryTimeRange') THEN
    ALTER TABLE "FishingEntries" ADD "FishingStartedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428094848_AddFishingEntryTimeRange') THEN
    CREATE INDEX "IX_FishingEntries_UserId_FishingStartedAt" ON "FishingEntries" ("UserId", "FishingStartedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428094848_AddFishingEntryTimeRange') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260428094848_AddFishingEntryTimeRange', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507075532_AddPointVisibility') THEN
    ALTER TABLE "PointsOfInterest" ADD "IsVisibleOnMap" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507075532_AddPointVisibility') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260507075532_AddPointVisibility', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508063556_AddFishingEntrySocialActions') THEN
    CREATE TABLE "FishingEntryComments" (
        "Id" uuid NOT NULL,
        "FishingEntryId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Text" character varying(1000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_FishingEntryComments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FishingEntryComments_FishingEntries_FishingEntryId" FOREIGN KEY ("FishingEntryId") REFERENCES "FishingEntries" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FishingEntryComments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508063556_AddFishingEntrySocialActions') THEN
    CREATE TABLE "FishingEntryLikes" (
        "Id" uuid NOT NULL,
        "FishingEntryId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FishingEntryLikes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FishingEntryLikes_FishingEntries_FishingEntryId" FOREIGN KEY ("FishingEntryId") REFERENCES "FishingEntries" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FishingEntryLikes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508063556_AddFishingEntrySocialActions') THEN
    CREATE TABLE "FishingEntryShares" (
        "Id" uuid NOT NULL,
        "FishingEntryId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FishingEntryShares" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FishingEntryShares_FishingEntries_FishingEntryId" FOREIGN KEY ("FishingEntryId") REFERENCES "FishingEntries" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FishingEntryShares_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508063556_AddFishingEntrySocialActions') THEN
    CREATE INDEX "IX_FishingEntryComments_FishingEntryId" ON "FishingEntryComments" ("FishingEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508063556_AddFishingEntrySocialActions') THEN
    CREATE INDEX "IX_FishingEntryComments_UserId" ON "FishingEntryComments" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508063556_AddFishingEntrySocialActions') THEN
    CREATE UNIQUE INDEX "IX_FishingEntryLikes_FishingEntryId_UserId" ON "FishingEntryLikes" ("FishingEntryId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508063556_AddFishingEntrySocialActions') THEN
    CREATE INDEX "IX_FishingEntryLikes_UserId" ON "FishingEntryLikes" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508063556_AddFishingEntrySocialActions') THEN
    CREATE INDEX "IX_FishingEntryShares_FishingEntryId" ON "FishingEntryShares" ("FishingEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508063556_AddFishingEntrySocialActions') THEN
    CREATE INDEX "IX_FishingEntryShares_UserId" ON "FishingEntryShares" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508063556_AddFishingEntrySocialActions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260508063556_AddFishingEntrySocialActions', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508073211_AddFeedCommentRepliesAndChatShares') THEN
    DROP INDEX "IX_FishingEntryComments_FishingEntryId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508073211_AddFeedCommentRepliesAndChatShares') THEN
    ALTER TABLE "FishingEntryComments" ADD "ParentCommentId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508073211_AddFeedCommentRepliesAndChatShares') THEN
    ALTER TABLE "ChatMessages" ADD "SharedFishingEntryId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508073211_AddFeedCommentRepliesAndChatShares') THEN
    CREATE INDEX "IX_FishingEntryComments_FishingEntryId_ParentCommentId_Created~" ON "FishingEntryComments" ("FishingEntryId", "ParentCommentId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508073211_AddFeedCommentRepliesAndChatShares') THEN
    CREATE INDEX "IX_FishingEntryComments_ParentCommentId" ON "FishingEntryComments" ("ParentCommentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508073211_AddFeedCommentRepliesAndChatShares') THEN
    CREATE INDEX "IX_ChatMessages_SharedFishingEntryId" ON "ChatMessages" ("SharedFishingEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508073211_AddFeedCommentRepliesAndChatShares') THEN
    ALTER TABLE "ChatMessages" ADD CONSTRAINT "FK_ChatMessages_FishingEntries_SharedFishingEntryId" FOREIGN KEY ("SharedFishingEntryId") REFERENCES "FishingEntries" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508073211_AddFeedCommentRepliesAndChatShares') THEN
    ALTER TABLE "FishingEntryComments" ADD CONSTRAINT "FK_FishingEntryComments_FishingEntryComments_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES "FishingEntryComments" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508073211_AddFeedCommentRepliesAndChatShares') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260508073211_AddFeedCommentRepliesAndChatShares', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508152229_AddVerificationCodes') THEN
    CREATE TABLE "VerificationCodes" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Purpose" character varying(50) NOT NULL,
        "CodeHash" character varying(128) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "UsedAt" timestamp with time zone,
        "FailedAttempts" integer NOT NULL,
        "MaxAttempts" integer NOT NULL,
        "SentTo" character varying(256),
        "IpAddress" character varying(64),
        CONSTRAINT "PK_VerificationCodes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VerificationCodes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508152229_AddVerificationCodes') THEN
    CREATE INDEX "IX_VerificationCodes_UserId_Purpose_CreatedAt" ON "VerificationCodes" ("UserId", "Purpose", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508152229_AddVerificationCodes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260508152229_AddVerificationCodes', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260509110350_AddUserFirstNameLastName') THEN
    ALTER TABLE "Users" ADD "FirstName" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260509110350_AddUserFirstNameLastName') THEN
    ALTER TABLE "Users" ADD "LastName" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260509110350_AddUserFirstNameLastName') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260509110350_AddUserFirstNameLastName', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260510152754_AddCompanionSearchLogic') THEN
    DROP INDEX "IX_CompanionResponses_RequestId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260510152754_AddCompanionSearchLogic') THEN
    ALTER TABLE "CompanionResponses" ADD "Status" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260510152754_AddCompanionSearchLogic') THEN
    ALTER TABLE "CompanionRequests" ADD "SeatsCount" integer NOT NULL DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260510152754_AddCompanionSearchLogic') THEN
    CREATE UNIQUE INDEX "IX_CompanionResponses_RequestId_UserId" ON "CompanionResponses" ("RequestId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260510152754_AddCompanionSearchLogic') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260510152754_AddCompanionSearchLogic', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511115350_AddChatReadStates') THEN
    CREATE TABLE "ChatReadStates" (
        "Id" uuid NOT NULL,
        "ChatId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "LastReadAt" timestamp with time zone,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ChatReadStates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatReadStates_Chats_ChatId" FOREIGN KEY ("ChatId") REFERENCES "Chats" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ChatReadStates_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511115350_AddChatReadStates') THEN
    CREATE UNIQUE INDEX "IX_ChatReadStates_ChatId_UserId" ON "ChatReadStates" ("ChatId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511115350_AddChatReadStates') THEN
    CREATE INDEX "IX_ChatReadStates_UserId" ON "ChatReadStates" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511115350_AddChatReadStates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260511115350_AddChatReadStates', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511131527_AddFishingEntryMedia') THEN
    CREATE TABLE "FishingEntryMedia" (
        "Id" uuid NOT NULL,
        "FishingEntryId" uuid NOT NULL,
        "Url" character varying(500) NOT NULL,
        "MediaType" character varying(20) NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FishingEntryMedia" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FishingEntryMedia_FishingEntries_FishingEntryId" FOREIGN KEY ("FishingEntryId") REFERENCES "FishingEntries" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511131527_AddFishingEntryMedia') THEN
    CREATE INDEX "IX_FishingEntryMedia_FishingEntryId_SortOrder" ON "FishingEntryMedia" ("FishingEntryId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511131527_AddFishingEntryMedia') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260511131527_AddFishingEntryMedia', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527190515_AddPersonalDataConsentToUsers') THEN
    ALTER TABLE "Users" ADD "PersonalDataConsentAccepted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527190515_AddPersonalDataConsentToUsers') THEN
    ALTER TABLE "Users" ADD "PersonalDataConsentAcceptedAtUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527190515_AddPersonalDataConsentToUsers') THEN
    ALTER TABLE "Users" ADD "PersonalDataConsentIp" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527190515_AddPersonalDataConsentToUsers') THEN
    ALTER TABLE "Users" ADD "PersonalDataConsentUserAgent" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527190515_AddPersonalDataConsentToUsers') THEN
    ALTER TABLE "Users" ADD "PersonalDataConsentVersion" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527190515_AddPersonalDataConsentToUsers') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260527190515_AddPersonalDataConsentToUsers', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529095425_AddUserLastSeenAtUtc') THEN
    ALTER TABLE "Users" ADD "LastSeenAtUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529095425_AddUserLastSeenAtUtc') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260529095425_AddUserLastSeenAtUtc', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530051557_AddLegalConsentTracking') THEN
    ALTER TABLE "Users" ADD "PersonalDataDistributionConsentAccepted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530051557_AddLegalConsentTracking') THEN
    ALTER TABLE "Users" ADD "PersonalDataDistributionConsentAcceptedAtUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530051557_AddLegalConsentTracking') THEN
    ALTER TABLE "Users" ADD "PersonalDataDistributionConsentIp" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530051557_AddLegalConsentTracking') THEN
    ALTER TABLE "Users" ADD "PersonalDataDistributionConsentUserAgent" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530051557_AddLegalConsentTracking') THEN
    ALTER TABLE "Users" ADD "PersonalDataDistributionConsentVersion" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530051557_AddLegalConsentTracking') THEN
    ALTER TABLE "Users" ADD "UserAgreementAccepted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530051557_AddLegalConsentTracking') THEN
    ALTER TABLE "Users" ADD "UserAgreementAcceptedAtUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530051557_AddLegalConsentTracking') THEN
    ALTER TABLE "Users" ADD "UserAgreementIp" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530051557_AddLegalConsentTracking') THEN
    ALTER TABLE "Users" ADD "UserAgreementUserAgent" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530051557_AddLegalConsentTracking') THEN
    ALTER TABLE "Users" ADD "UserAgreementVersion" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530051557_AddLegalConsentTracking') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260530051557_AddLegalConsentTracking', '8.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530114600_AddNotificationSettings') THEN
    ALTER TABLE "Users" ADD "ChatToastsEnabled" boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530114600_AddNotificationSettings') THEN
    ALTER TABLE "Users" ADD "HideChatMessageTextInNotifications" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530114600_AddNotificationSettings') THEN
    ALTER TABLE "PrivateChatUserStates" ADD "IsMuted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530114600_AddNotificationSettings') THEN
    ALTER TABLE "ChatParticipants" ALTER COLUMN "IsMuted" SET DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260530114600_AddNotificationSettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260530114600_AddNotificationSettings', '8.0.10');
    END IF;
END $EF$;
COMMIT;

